"""Update Table Field

Revision ID: 0b4d2cfc0139
Revises: d4fa7d7c5bf8
Create Date: 2026-01-27 13:16:14.875301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b4d2cfc0139'
down_revision: Union[str, Sequence[str], None] = 'd4fa7d7c5bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_analysis_sessions', sa.Column('summary', sa.Text(), nullable=True))
    op.drop_column('cv_analysis_sessions', 'error_message')
    op.drop_column('cv_analysis_sessions', 'overall_score')
    op.drop_column('cv_analysis_sessions', 'analysis_type')
    op.drop_column('cv_analysis_sessions', 'processing_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_analysis_sessions', sa.Column('processing_time', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cv_analysis_sessions', sa.Column('analysis_type', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('cv_analysis_sessions', sa.Column('overall_score', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('cv_analysis_sessions', sa.Column('error_message', mysql.TEXT(), nullable=True))
    op.drop_column('cv_analysis_sessions', 'summary')
    # ### end Alembic commands ###
