"""Update not nullable in role user table

Revision ID: 11c108ec3784
Revises: e0e21fc0fcac
Create Date: 2025-12-07 01:26:08.569055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11c108ec3784'
down_revision: Union[str, Sequence[str], None] = 'e0e21fc0fcac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
