"""Add new table

Revision ID: 1b4564e124ae
Revises: 30749e23191b
Create Date: 2026-01-27 17:25:07.047902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.entities.base_entity import GUID

# revision identifiers, used by Alembic.
revision: str = '1b4564e124ae'
down_revision: Union[str, Sequence[str], None] = '30749e23191b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_keywords',
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['cv_analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_keywords')
    # ### end Alembic commands ###
