"""Remove table

Revision ID: 3c302b3d421a
Revises: b72e8dbcee80
Create Date: 2026-01-27 02:18:21.220345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c302b3d421a'
down_revision: Union[str, Sequence[str], None] = 'b72e8dbcee80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('ai_model_performance')
    # op.drop_index(op.f('idx_analysis_model'), table_name='ai_analysis_results')
    # op.drop_index(op.f('idx_analysis_session'), table_name='ai_analysis_results')
    op.drop_table('ai_analysis_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_results',
    sa.Column('session_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('ai_model_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('result_data', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('confidence_score', mysql.FLOAT(), nullable=False),
    sa.Column('analyzed_at', mysql.DATETIME(), nullable=False),
    sa.Column('raw_response', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], name=op.f('ai_analysis_results_ibfk_1')),
    sa.ForeignKeyConstraint(['session_id'], ['cv_analysis_sessions.id'], name=op.f('ai_analysis_results_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_analysis_session'), 'ai_analysis_results', ['session_id'], unique=False)
    op.create_index(op.f('idx_analysis_model'), 'ai_analysis_results', ['ai_model_id'], unique=False)
    op.create_table('ai_model_performance',
    sa.Column('avg_score', mysql.FLOAT(), nullable=False),
    sa.Column('total_analyses', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_processing_time', mysql.FLOAT(), nullable=False),
    sa.Column('sucess_rate', mysql.FLOAT(), nullable=False),
    sa.Column('model_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], name=op.f('ai_model_performance_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
