"""Update Tables

Revision ID: 42b15a9414fe
Revises: 88f5f6816aec
Create Date: 2026-01-27 00:27:28.514799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '42b15a9414fe'
down_revision: Union[str, Sequence[str], None] = '88f5f6816aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'user_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'user_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
