"""Update Table

Revision ID: 517982a4209b
Revises: 42b15a9414fe
Create Date: 2026-01-27 01:15:38.491607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '517982a4209b'
down_revision: Union[str, Sequence[str], None] = '42b15a9414fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('media_files_ibfk_1'), 'media_files', type_='foreignkey')
    op.drop_column('media_files', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('user_id', mysql.CHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('media_files_ibfk_1'), 'media_files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
