"""Add title to recommendation

Revision ID: 5a7d1a08f161
Revises: 689656df0ca6
Create Date: 2026-01-27 14:11:58.696660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7d1a08f161'
down_revision: Union[str, Sequence[str], None] = '689656df0ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_recommendations', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_recommendations', 'title')
    # ### end Alembic commands ###
