"""convert models to sqlalchemy 2.0 mapped_column

Revision ID: 64094a3d6662
Revises: 11c108ec3784
Create Date: 2026-01-17 02:33:32.848308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from src.entities.base_entity import GUID

# revision identifiers, used by Alembic.
revision: str = '64094a3d6662'
down_revision: Union[str, Sequence[str], None] = '11c108ec3784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_missing_skills',
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('skill_id', GUID(), nullable=False),
    sa.Column('importance', sa.String(length=50), nullable=False),
    sa.Column('detected_level', sa.String(length=50), nullable=True),
    sa.Column('required_level', sa.String(length=50), nullable=True),
    sa.Column('gap_analysis', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.CheckConstraint('importance >= 1 AND importance <= 5', name='check_importance_range'),
    sa.ForeignKeyConstraint(['session_id'], ['cv_analysis_sessions.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_format_issues',
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('analysis_id', GUID(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_weaknesses',
    sa.Column('weakness_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('analysis_id', GUID(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_weaknesses_type', 'analysis_weaknesses', ['weakness_type'], unique=False)
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'user_cv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_cv', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'role_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_verified')
    op.drop_column('roles', 'description')
    op.drop_index('idx_analysis_weaknesses_type', table_name='analysis_weaknesses')
    op.drop_table('analysis_weaknesses')
    op.drop_table('analysis_format_issues')
    op.drop_table('session_missing_skills')
    # ### end Alembic commands ###
