"""Add new Tables

Revision ID: 689656df0ca6
Revises: 73555d05f2fd
Create Date: 2026-01-27 14:02:15.539515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.entities.base_entity import GUID

# revision identifiers, used by Alembic.
revision: str = '689656df0ca6'
down_revision: Union[str, Sequence[str], None] = '73555d05f2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['cv_analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_session_id'), 'questions', ['session_id'], unique=False)
    op.create_table('session_skill_gaps',
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('learning_keyword', sa.String(length=255), nullable=False),
    sa.Column('skill_gap', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['cv_analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_skill_gaps_session_id'), 'session_skill_gaps', ['session_id'], unique=False)
    op.create_table('skill_gap_resource_types',
    sa.Column('skill_gap_id', GUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['skill_gap_id'], ['session_skill_gaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gap_resource_types_skill_gap_id'), 'skill_gap_resource_types', ['skill_gap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_gap_resource_types_skill_gap_id'), table_name='skill_gap_resource_types')
    op.drop_table('skill_gap_resource_types')
    op.drop_index(op.f('ix_session_skill_gaps_session_id'), table_name='session_skill_gaps')
    op.drop_table('session_skill_gaps')
    op.drop_index(op.f('ix_questions_session_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
