"""Update Session Table

Revision ID: 88f5f6816aec
Revises: 64094a3d6662
Create Date: 2026-01-26 17:16:41.027395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88f5f6816aec'
down_revision: Union[str, Sequence[str], None] = '64094a3d6662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cv_analysis_sessions', 'user_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    op.alter_column('cv_analysis_sessions', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cv_analysis_sessions', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cv_analysis_sessions', 'user_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
