"""Add evaluate

Revision ID: a2f46bad9e87
Revises: e1b1d29140d6
Create Date: 2026-02-23 20:07:25.922936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f46bad9e87'
down_revision: Union[str, Sequence[str], None] = 'e1b1d29140d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_analysis_sessions', sa.Column('evaluate', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_analysis_sessions', 'evaluate')
    # ### end Alembic commands ###
