"""Update

Revision ID: af3843c879f7
Revises: 74ccc5d3859e
Create Date: 2026-01-27 17:32:10.467186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af3843c879f7'
down_revision: Union[str, Sequence[str], None] = '74ccc5d3859e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_keywords', 'name',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_keywords', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###
