"""Remove tables

Revision ID: b72e8dbcee80
Revises: ba06d2dc8124
Create Date: 2026-01-27 02:11:31.399879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b72e8dbcee80'
down_revision: Union[str, Sequence[str], None] = 'ba06d2dc8124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('idx_analysis_model'), table_name='ai_analysis_results')
    # op.drop_index(op.f('idx_analysis_session'), table_name='ai_analysis_results')
    # op.drop_table('ai_analysis_results')
    op.drop_table('analysis_format_issues')
    # op.drop_index(op.f('idx_analysis_weaknesses_type'), table_name='analysis_weaknesses')
    op.drop_table('analysis_weaknesses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_weaknesses',
    sa.Column('weakness_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('severity', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('analysis_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis_results.id'], name=op.f('analysis_weaknesses_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_analysis_weaknesses_type'), 'analysis_weaknesses', ['weakness_type'], unique=False)
    op.create_table('analysis_format_issues',
    sa.Column('issue_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('analysis_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis_results.id'], name=op.f('analysis_format_issues_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ai_analysis_results',
    sa.Column('session_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('ai_model_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('result_data', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('confidence_score', mysql.FLOAT(), nullable=False),
    sa.Column('analyzed_at', mysql.DATETIME(), nullable=False),
    sa.Column('raw_response', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], name=op.f('ai_analysis_results_ibfk_1')),
    sa.ForeignKeyConstraint(['session_id'], ['cv_analysis_sessions.id'], name=op.f('ai_analysis_results_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_analysis_session'), 'ai_analysis_results', ['session_id'], unique=False)
    op.create_index(op.f('idx_analysis_model'), 'ai_analysis_results', ['ai_model_id'], unique=False)
    # ### end Alembic commands ###
