"""Update nullable

Revision ID: cab01bf89dda
Revises: e9e360232748
Create Date: 2026-01-27 14:38:41.291412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cab01bf89dda'
down_revision: Union[str, Sequence[str], None] = 'e9e360232748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_recommendations', 'article_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    op.alter_column('article_recommendations', 'reason',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('article_recommendations', 'priority',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_recommendations', 'priority',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('article_recommendations', 'reason',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('article_recommendations', 'article_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
