"""Update Table Field

Revision ID: d4fa7d7c5bf8
Revises: 3c302b3d421a
Create Date: 2026-01-27 02:34:13.359816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fa7d7c5bf8'
down_revision: Union[str, Sequence[str], None] = '3c302b3d421a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article_tag_mappings', 'article_tags', ['tag_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_tag_mappings', type_='foreignkey')
    # ### end Alembic commands ###
