"""Update User and Role  relations

Revision ID: e0e21fc0fcac
Revises: 65961362d054
Create Date: 2025-12-07 01:13:27.523102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.entities.base_entity import GUID

# revision identifiers, used by Alembic.
revision: str = 'e0e21fc0fcac'
down_revision: Union[str, Sequence[str], None] = '65961362d054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', GUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
