"""Update Table Field

Revision ID: e1b1d29140d6
Revises: af3843c879f7
Create Date: 2026-02-22 16:57:01.677534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.entities.base_entity import GUID

# revision identifiers, used by Alembic.
revision: str = 'e1b1d29140d6'
down_revision: Union[str, Sequence[str], None] = 'af3843c879f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('question_id', GUID(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('updated_by', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    # ### end Alembic commands ###
