"""Add fields to recommendation

Revision ID: e9e360232748
Revises: 5a7d1a08f161
Create Date: 2026-01-27 14:14:54.633634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e360232748'
down_revision: Union[str, Sequence[str], None] = '5a7d1a08f161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_recommendations', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_recommendations', 'url')
    # ### end Alembic commands ###
